spring:
    cloud:
        gcp:
            sql:
                enabled: true
                database-type: mysql
                database-name: ${database_name}
                instance-connection-name: ${instance_connection_name} 