spring:
    cloud:
        gcp:
            sql:
                enabled: true
                database-type: mysql
                database-name: marketplace
                instance-connection-name: qwiklabs-gcp-00-5c5c02051470:us-central1:mysql-db-container 