spring:
    cloud:
        gcp:
            sql:
                enabled: true
                database-type: mysql
                database-name: marketplace
                instance-connection-name: qwiklabs-gcp-04-62ba305b3be6:us-central1:mysql-db-container 