server:
    port: ${SERVER_PORT:8080}

spring:
    profiles:
        active: gcp,mysql
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://${database_name}/?cloudSqlInstance=${instance_connection_name}&socketFactory=com.google.cloud.sql.mysql.SocketFactory
        password: ${db_password:tpm1234}
        username: ${db_username:root}
        initialization-mode: always
        schema: classpath:/schema.sql
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        hibernate.ddl-auto: update
        show-sql: true