spring:
    cloud:
        gcp:
            sql:
                enabled: true
                database-type: mysql
                database-name: marketplace
                instance-connection-name: qwiklabs-gcp-5b1b48f5116cfae8:us-central1:mysql-db-container 