spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://google/marketplace?cloudSqlInstance=qwiklabs-gcp-00-8420f466804f:us-central1:mysql-db-container&socketFactory=com.google.cloud.sql.mysql.SocketFactory
        username: ${USER_ID:root}
        password: ${PASSWORD:tpm1234}
        initialization-mode: always
        schema: classpath:/schema.sql
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect