#set up properties

spring:
    profiles:
        active: gcp,mysql
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://google/marketplace?cloudSqlInstance=qwiklabs-gcp-00-8389f14457c7:us-central1:marketplace&socketFactory=com.google.cloud.sql.mysql.SocketFactory
        password: ${SECRETS_PASSWORD:tpm1234}
        username: ${SECRETS_USER:root}
        initialization-mode: always
        schema: classpath:/schema.sql
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        hibernate.ddl-auto: update
        show-sql: true