spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${RDS_HOSTNAME:127.0.0.1}:${RDS_PORT:3306}/${RDS_DB_NAME:marketplace}?createDatabaseIfNotExist=true
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://google/marketplace?cloudSqlInstance=qwiklabs-gcp-d30f23cf0764a75f:us-central1:mysql-db-container&socketFactory=com.google.cloud.sql.mysql.SocketFactory
        password: ${SECRETS_PASSWORD:tpm1234}
        username: ${SECRETS_USER:root}
        initialization-mode: always
        schema: classpath:/schema.sql
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect