spring:
    cloud:
        gcp:
            sql:
                enabled: true
                database-type: mysql
                database-name: marketplace
                instance-connection-name: qwiklabs-gcp-491d3f80a4fe1e82:us-central1:mysql-db-container 